### ISSUE TITLE
Kodi 19 Matrix Python 3

### ISSUE THREAD

**Issue by ghost** [tturkalj/service.subtitles.titlovi-com-official#3]
Hi,
Could you please update titlovi addon to python 3 and keep python 2 as well, I'm using Kodi matrix 19 and there's not subtitles addon at all to install. I use manly titlovi becose of ex-yu subs. Please Thanks

**Comment by tturkalj** [comment]
I'll see what I can do. In the meantime, feel free to submit pull request with your fix.

**Comment by ghost** [comment]
Fala. Ako ja uspjenem ista uraditi javiću. Neznam još Python 3 ali probacu.

**Comment by tturkalj** [comment]
Pull request is created: https://github.com/xbmc/repo-scripts/pull/1905
I will close this issue when pull request is merged.

**Comment by tturkalj** [comment]
Update is merged to official repository, closing this issue.
